site_name: IVOA Documentation Reimagined
docs_dir: doc
repo_url: 'https://github.com/ivoa/vo-dml'
edit_uri: 'edit/master/doc/'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - Home: index.md
  - Fundamentals:
      - DALI: generated/DALI/DALI.md
      - UWS: generated/UWS/UWS.md
      - VOTable: generated/VOTable/VOTable.md
  - Registry:
      - VOResource: generated/VOResource/VOResource.md
      - VODataService: generated/VODataService/VODataService.md
      - RegTAP: generated/RegTAP/RegTAP.md
  - TAP:
      - TAP: generated/TAP/TAP.md
      - ADQL: generated/ADQL/ADQL.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - attr_list
  - markdown_grid_tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - plantuml_markdown:
      format: svg
      remove_inline_svg_size: false
      cachedir: build/generated/plantuml
  - pymdownx.snippets:
      url_download: true