
name: Run Sphinx

env:
  doc_name   : VodmlTools
  branch_name: ${{ github.head_ref || github.ref_name }}
  tag_preview: note-auto-pdf-preview

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Prebuilt image should contain:
    # pandoc, texlive packages, plantuml + Java, python deps (or at least python3/pip)
    container:
      image: ghcr.io/ivoa/ivoadocviewsite-sphinx-build:latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Site
      run: |
        make
        make restore_ivoatex
     # https://docs.github.com/en/actions/tutorials/store-and-share-data
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: ivoa_site_build
          path: build/




